<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-14T22:06:38 IST" name="Suite" finished-at="2023-12-14T22:11:06 IST" duration-ms="267854">
    <groups>
    </groups>
    <test started-at="2023-12-14T22:06:38 IST" name="Test" finished-at="2023-12-14T22:11:06 IST" duration-ms="267854">
      <class name="TestNGScript.Assert12">
        <test-method is-config="true" signature="openAppln()[pri:0, instance:TestNGScript.Assert12@3c73951]" started-at="2023-12-14T22:09:36 IST" name="openAppln" finished-at="2023-12-14T22:09:49 IST" duration-ms="13687" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="facebook()[pri:0, instance:TestNGScript.Assert12@3c73951]" started-at="2023-12-14T22:09:49 IST" name="facebook" finished-at="2023-12-14T22:10:28 IST" duration-ms="39052" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebook -->
        <test-method is-config="true" signature="closeAppln()[pri:0, instance:TestNGScript.Assert12@3c73951]" started-at="2023-12-14T22:10:28 IST" name="closeAppln" finished-at="2023-12-14T22:10:33 IST" duration-ms="4643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
        <test-method is-config="true" signature="openAppln()[pri:0, instance:TestNGScript.Assert12@3c73951]" started-at="2023-12-14T22:10:33 IST" name="openAppln" finished-at="2023-12-14T22:10:52 IST" duration-ms="19484" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="login()[pri:0, instance:TestNGScript.Assert12@3c73951]" started-at="2023-12-14T22:10:52 IST" name="login" finished-at="2023-12-14T22:10:58 IST" duration-ms="5758" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [actiTIME] but found [actiTIME - Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [actiTIME] but found [actiTIME - Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestNGScript.Assert12.login(Assert12.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closeAppln()[pri:0, instance:TestNGScript.Assert12@3c73951]" started-at="2023-12-14T22:10:58 IST" name="closeAppln" finished-at="2023-12-14T22:11:06 IST" duration-ms="7872" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
      </class> <!-- TestNGScript.Assert12 -->
      <class name="TestNGScript.Assert">
        <test-method is-config="true" signature="openAppln()[pri:0, instance:TestNGScript.Assert@41e1e210]" started-at="2023-12-14T22:06:38 IST" name="openAppln" finished-at="2023-12-14T22:07:18 IST" duration-ms="40162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="facebook()[pri:0, instance:TestNGScript.Assert@41e1e210]" started-at="2023-12-14T22:07:18 IST" name="facebook" finished-at="2023-12-14T22:08:58 IST" duration-ms="99866" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebook -->
        <test-method is-config="true" signature="closeAppln()[pri:0, instance:TestNGScript.Assert@41e1e210]" started-at="2023-12-14T22:08:58 IST" name="closeAppln" finished-at="2023-12-14T22:09:08 IST" duration-ms="9748" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
        <test-method is-config="true" signature="openAppln()[pri:0, instance:TestNGScript.Assert@41e1e210]" started-at="2023-12-14T22:09:08 IST" name="openAppln" finished-at="2023-12-14T22:09:24 IST" duration-ms="16134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="login()[pri:0, instance:TestNGScript.Assert@41e1e210]" started-at="2023-12-14T22:09:24 IST" name="login" finished-at="2023-12-14T22:09:30 IST" duration-ms="5730" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [actiTIME] but found [actiTIME - Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [actiTIME] but found [actiTIME - Login]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestNGScript.Assert.login(Assert.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closeAppln()[pri:0, instance:TestNGScript.Assert@41e1e210]" started-at="2023-12-14T22:09:30 IST" name="closeAppln" finished-at="2023-12-14T22:09:36 IST" duration-ms="5560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
      </class> <!-- TestNGScript.Assert -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
